#!/usr/bin/env node
// Build-time: fetch every scraper provider from the configured Nuvio plugin repos,
// transpile each to chrome-47-compatible JS with Babel (keeps generators/arrows,
// lowers default params + destructuring), and emit a bundled map the runtime engine
// reads. No on-device transpiler / no server needed at runtime — the TV runs the
// pre-transpiled providers locally. Re-run to refresh providers.
import { transformSync } from "@babel/core";
import { writeFileSync, readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(__dirname, "..", "js", "core", "player", "providers.generated.js");
const REPOS_CONFIG = path.join(__dirname, "plugin-repos.json");

// The plugin repos (raw base URLs) live in scripts/plugin-repos.json so they can be
// edited without touching this script — add a repo there and re-run, or let the
// GitHub Action (.github/workflows/build-tizen-plugins.yml) regenerate the bundle.
const REPOS = (() => {
  try {
    const parsed = JSON.parse(readFileSync(REPOS_CONFIG, "utf8"));
    const list = Array.isArray(parsed?.repos) ? parsed.repos : [];
    return list.filter((repo) => repo && repo.id && repo.base);
  } catch (e) {
    console.error(`[fatal] cannot read ${REPOS_CONFIG}: ${e.message}`);
    process.exit(1);
  }
})();

async function getText(url) {
  const r = await fetch(url);
  if (!r.ok) throw new Error(`HTTP ${r.status} ${url}`);
  return r.text();
}

function transpile(code) {
  return transformSync(code, {
    presets: [["@babel/preset-env", { targets: "chrome 47" }]],
    compact: true, comments: false, sourceType: "script",
  }).code;
}

const providers = [];
for (const repo of REPOS) {
  let manifest;
  try { manifest = JSON.parse(await getText(repo.base + "manifest.json")); }
  catch (e) { console.error(`[skip repo ${repo.id}] ${e.message}`); continue; }
  const scrapers = manifest.scrapers || [];
  for (const sc of scrapers) {
    if (sc.enabled === false) continue;
    const file = sc.filename || `providers/${sc.id}.js`;
    try {
      const raw = await getText(repo.base + file);
      const code = transpile(raw);
      providers.push({
        repoId: repo.id, repoName: manifest.name || repo.id,
        id: sc.id, name: sc.name || sc.id,
        types: sc.supportedTypes || ["movie", "tv"],
        needsCheerio: /require\(["']cheerio/.test(raw),
        code,
      });
      console.error(`[ok] ${repo.id}/${sc.id} (${raw.length}->${code.length}b)`);
    } catch (e) {
      console.error(`[skip ${repo.id}/${sc.id}] ${e.message}`);
    }
  }
}

// dedupe by scraper id (keep first)
const seen = new Set();
const deduped = providers.filter((p) => (seen.has(p.id) ? false : (seen.add(p.id), true)));

const banner = `// AUTO-GENERATED by scripts/build-plugins.mjs — do not edit.\n// ${deduped.length} providers, transpiled to chrome 47.\n`;
const body = `export const GENERATED_PROVIDERS = ${JSON.stringify(deduped)};\n`;
writeFileSync(OUT, banner + body);
console.error(`\nWROTE ${deduped.length} providers -> ${OUT}`);
